name: lanai
description: An images showcase app built using flutter.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    freezed_annotation: ^1.1.0
    http: ^0.13.4
    json_annotation: ^4.4.0
    json_serializable: ^6.1.4
    meta: ^1.7.0
    cupertino_icons: ^1.0.2
    provider: ^6.0.2
    flutter_staggered_grid_view: ^0.6.1
    url_launcher: ^6.0.20
    url_launcher_web: ^2.0.8
    share_plus: ^3.1.0
    state_notifier: ^0.7.2+1
    flutter_state_notifier: ^0.7.1
    extended_image: ^6.0.1
    chewie: ^1.3.0
    video_player: ^2.2.19
    material_floating_search_bar: ^0.3.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.1.7
    freezed: ^1.1.1
    mockito: ^5.1.0
    flutter_lints: ^1.0.4

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/
    fonts:
        - family: Caveat
          fonts:
              - asset: assets/fonts/Caveat-Regular.ttf
        - family: Dongle
          fonts:
              - asset: assets/fonts/Dongle-Regular.ttf
